---
- name: Setup contented to run as a service on a linux machine (make build-linux first)
  hosts: all
  remote_user: "{{ run_user | default('contented_user') }}"

  vars:
    run_user: contented_user

  roles:
    - contented
