---
- name: Update the OS so that we can install go
  apt: pkg={{item}} state=installed update_cache=true
  become: true
  with_items:
    - curl
    - vim
    - wget

- import_tasks: permissions.yml

- import_tasks: go.yml
- name: Copy contented binary to /usr/local/bin
  copy:
    src: "{{ src_dir }}/contented"
    dest: "/usr/local/bin/contented"
    mode: '0755'
  become: true

- name: Create contented systemd service file
  template:
    src: contented.service.j2
    dest: /etc/systemd/system/contented.service
  become: true

- name: Ensure contented service is enabled and started
  systemd:
    name: contented
    enabled: yes
    state: started
  become: true
  when: ansible_service_mgr == 'systemd'

- name: Create contented init.d script (for non-systemd systems)
  template:
    src: contented.init.j2
    dest: /etc/init.d/contented
    mode: '0755'
  become: true
  when: ansible_service_mgr != 'systemd'

- name: Ensure contented service is enabled and started (for non-systemd systems)
  service:
    name: contented
    enabled: yes
    state: started
  become: true
  when: ansible_service_mgr != 'systemd'
