- name: Install Node.js repository (Latest LTS version)
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Yarn
  npm:
    name: yarn
    global: yes
  become: true

- name: Run yarn install
  yarn:
    path: "{{ project_root }}"
  become: false

- name: Run makefile typescript target
  make:
    chdir: "{{ project_root }}"
    target: typescript
  become: false


