- name: Add the Go official repository
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Update apt cache
  apt:
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Go on Ubuntu
  apt:
    name: golang-go
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Go on Amazon Linux
  yum:
    name: golang
    state: present
  become: true
  when: ansible_distribution == 'Amazon'

- name: Set GOPATH in .bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export GOPATH=$HOME/go"
    state: present

- name: Add GOPATH/bin to PATH in .bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export PATH=$PATH:$GOPATH/bin"
    state: present

- name: Create GOPATH directory
  file:
    path: "/home/{{ ansible_user }}/go"
    state: directory
    mode: '0755'

- name: Reload .bashrc
  shell: source "/home/{{ ansible_user }}/.bashrc"
