package actions

import (
	"contented/managers"
	"contented/models"
	"log"

	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gobuffalo/buffalo"
	"github.com/gofrs/uuid"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Container)
// DB Table: Plural (containers)
// Resource: Plural (Containers)
// Path: Plural (/containers)
// View Template Folder: Plural (/templates/containers/)

type ContainersResponse struct {
	Total   int               `json:"total"`
	Results models.Containers `json:"results"`
}

// ContainersResource is the resource for the Container model
type ContainersResource struct {
	buffalo.Resource
}

// List gets all Containers. This function is mapped to the path
// GET /containers
func (v ContainersResource) List(c *gin.Context) error {
	// Get the DB connection from the context

	man := managers.GetManager(c)
	containers, total, err := man.ListContainersContext()
	if err != nil {
		return c.AbortWithError(http.StatusBadRequest, err)
	}
	log.Printf("Found %d containers", total)
	cr := ContainersResponse{
		Total:   total,
		Results: *containers,
	}
	c.JSON(200, cr)
	return nil
}

// Show gets the data for one Container. This function is mapped to
// the path GET /containers/{container_id}
func (v ContainersResource) Show(c *gin.Context) error {

	cID, err := uuid.FromString(c.Param("container_id"))
	if err != nil {
		return c.AbortWithError(http.StatusBadRequest, err)
	}

	// Get the DB connection from the context
	man := managers.GetManager(c)
	container, err := man.GetContainer(cID)
	if err != nil {
		return c.AbortWithError(http.StatusNotFound, err)
	}
	c.JSON(200, container)
	return nil
}

// Create adds a Container to the DB. This function is mapped to the
// path POST /containers
func (v ContainersResource) Create(c *gin.Context) error {
	// Allocate an empty Container
	man, _, err := managers.ManagerCanCUD(c)
	if err != nil {
		return err
	}

	// Bind container to the html form elements
	container := &models.Container{}
	if err := c.Bind(container); err != nil {
		return err
	}

	cfg := man.GetCfg()
	// IS-327 Reset the path for now
	container.Path = cfg.Dir

	c_err := man.CreateContainer(container)
	if c_err != nil {
		return c_err
	}
	validate, vErr := man.GetContainer(container.ID)
	if vErr != nil {
		return vErr
	}
	c.JSON(http.StatusCreated, validate)
	return nil
}

// Update changes a Container in the DB. This function is mapped to
// the path PUT /containers/{container_id}
func (v ContainersResource) Update(c *gin.Context) error {
	// Get the DB connection from the context
	man, _, err := managers.ManagerCanCUD(c)
	if err != nil {
		return c.AbortWithError(http.StatusNotImplemented, err)
	}

	// Allocate an empty Container
	id, idErr := uuid.FromString(c.Param("container_id"))
	if idErr != nil {
		return c.AbortWithError(http.StatusBadRequest, idErr)
	}
	// Bind Container to the html form elements (could toss the context into the manager)
	cnt, notFoundErr := man.GetContainer(id)
	if notFoundErr != nil {
		return c.AbortWithError(http.StatusNotFound, notFoundErr)
	}
	if err := c.Bind(cnt); err != nil {
		return c.AbortWithError(http.StatusBadRequest, err)
	}
	upCnt, upErr := man.UpdateContainer(cnt)
	if upErr != nil {
		return c.AbortWithError(http.StatusInternalServerError, upErr)
	}
	c.JSON(http.StatusOK, upCnt)
	return nil
}

// Destroy deletes a Container from the DB. This function is mapped
// to the path DELETE /containers/{container_id}
func (v ContainersResource) Destroy(c *gin.Context) error {
	// Get the DB connection from the context
	man, _, err := managers.ManagerCanCUD(c)
	if err != nil {
		return err
	}
	id := c.Param("container_id")
	cnt, dErr := man.DestroyContainer(id)
	if dErr != nil {
		if cnt == nil {
			return c.AbortWithError(http.StatusNotFound, dErr)
		} else {
			return c.AbortWithError(http.StatusUnprocessableEntity, dErr)
		}
	}
	c.JSON(http.StatusOK, cnt)
	return nil
}
